### ISSUE TITLE
Support for Wallet Connect 2.x...

### ISSUE THREAD

**Issue by patniemeyer** [y-pakorn/flutter_web3#56]
It looks like Wallet Connect is dropping support for their 1.x API soon and will require a shift to the 2.x APIs.  In conjunction with this they seem to have moved away from the Web3 interface to an ethereum provider API.

Are you planning to update the wallet connect support in `flutter_web3` for this?  (Thanks for your work on the project.)

**Comment by patniemeyer** [comment]
I have made a rough implementation of a flutter_web3 provider for WalletConnect v2.  At the moment this requires small modifications to `provider.dart` and `interop_wrapper.dart` to make it possible to use these outside of the package and allow the new ETH provider to work with the Web3 provider wrapper.  My project is open source so I'll post here again when the code is online in that form, but I'm wondering what if any plans @y-pakorn has for this project.  I'd be happy to submit a PR with my rough implementation of the whole thing...  Or, alternately, a very minimal patch that opens up the framework so that third parties can plug in their own implementations.

EDIT: To summarize the min changes it would really just be making the `Interop` class public (not internal) and broadening the assertion in `Web3Provider` factory so that it can wrap any dynamic `Interop` provider and not just the two it knows about.

**Comment by patniemeyer** [comment]
The rough but functional WalletConnect v2 implementation is here: `https://github.com/OrchidTechnologies/orchid/blob/master/web-ethereum/dapp2/lib/api/orchid_web3/wallet_connect_eth_provider.dart` and the small patch required to the core is here:  `https://github.com/OrchidTechnologies/orchid/blob/master/web-ethereum/dapp2/flutter_web3.patch`.  If there is any interest in this I could submit a PR.   

EDIT:  There is a small JS lib that exposes the provider (similar to what the UMD js file did for v1) here:  `https://github.com/OrchidTechnologies/orchid/tree/master/web-ethereum/dapp2/walletconnect`.

**Comment by 4xMafole** [comment]
Hi, @patniemeyer.
Good work. Would you mind sharing your fork/pull request so as we developers can utilize that. Seems, the package owner has not been active recently on this package.

Thanks.

**Comment by 4xMafole** [comment]
Hello, @patniemeyer.
Hope you're doing great. I passed through the shared repo, and I have seen the patch and the provider you made. Good work. I just have one issue on my end, I want to upgrade my project to use the v2. I followed the patch plus added the wallet_connect_eth_provider.dart, but still can't figure out what to do next.

Here is what I did:
1. Clone the flutter_web3
2. Did the changes as per your patch on the flutter_web3.
3. Added provider (wallet_connect_eth_provider) to my project.
4. (I don't know next to do)

Is there anything I am missing, it will be helpful if you provide a basic implementation of how to achieve the utilization of v2.
Also, I saw on the index.html your using relative urls for both ethers and walletconnect v2. But seems I can't find the absolute url for walletconnect js v2.

Hope to hear from you, soon. 

Thanks.

**Comment by 4xMafole** [comment]
> Hello, @patniemeyer. Hope you're doing great. I passed through the shared repo, and I have seen the patch and the provider you made. Good work. I just have one issue on my end, I want to upgrade my project to use the v2. I followed the patch plus added the wallet_connect_eth_provider.dart, but still can't figure out what to do next.
> 
> Here is what I did:
> 
> 1. Clone the flutter_web3
> 2. Did the changes as per your patch on the flutter_web3.
> 3. Added provider (wallet_connect_eth_provider) to my project.
> 4. (I don't know next to do)
> 
> Is there anything I am missing, it will be helpful if you provide a basic implementation of how to achieve the utilization of v2. Also, I saw on the index.html your using relative urls for both ethers and walletconnect v2. But seems I can't find the absolute url for walletconnect js v2.
> 
> Hope to hear from you, soon.
> 
> Thanks.

Also, I have seen you have created the library JS entry point for the WalletConnectEthereumProvider. But how can I utilize that, I little bit bigger to JS have with the right guide. I can do.

Thanks.

**Comment by patniemeyer** [comment]
> 
> Also, I have seen you have created the library JS entry point for the WalletConnectEthereumProvider. But how can I utilize that, I little bit bigger to JS have with the right guide. I can do.

I apologize for not having the time to do a proper fork of this project at the moment (I am still hoping that maybe @y-pakorn will update it?)

Anyway, please take a look at the `flutter_web3.sh` build script in my project:  https://github.com/OrchidTechnologies/orchid/blob/master/web-ethereum/dapp2/flutter_web3.sh

It checks out the flutter_web3 package, patches it, grabs the required ethers libs from the CDN, and builds my minimal `walletconnectv2.js` entry point.   I could not find a UMD style JS package for walletconnect v2 so I made this three line package, but I would love to get rid of it if possible.

**Comment by Maringmei** [comment]
[patniemeyer](https://github.com/patniemeyer) doesn't work at all here is the error : Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'default')
    at WalletConnectProvider.fromRpc (wallet_connect.dart.js:74:96)
    at WalletConnectProvider.binance (wallet_connect.dart.js:166:51)
