### ISSUE TITLE
WebSocket connection to ...  failed

### ISSUE THREAD

**Issue by Tepehan** [y-pakorn/flutter_web3#62]
I get this issue while this  code "WalletConnectProvider wc = WalletConnectProvider.binance();" is initialized.
**Uncaught (in promise) Error: Missing or invalid topic field
    at t.a.send (index.min.js:22:10858)
    at t.default._sendRequest (index.min.js:44:106035)
    at async t.default.killSession (index.min.js:44:103219)**
**WebSocket connection to 'wss://9.bridge.walletconnect.org/?env=browser&host=paymentsystem-3fb32.web.app&protocol=wc&version=1' failed:**
Anyone help?

**Comment by Tepehan** [comment]
Hey guys! are you going to fix it or not?
There is something that about the web3provider;
If you are using @walletconnect/web3-provider, we stopped supporting this provider in favor of the improved version published under @walletconnect/ethereum-provider and you will be able to check the latest version on NPM [here](https://npmjs.com/package/@walletconnect/ethereum-provider).
please check the link **https://docs.walletconnect.com/2.0/advanced/migration-from-v1.x/dapps**
